# Generated by Django 3.0.4 on 2020-03-25 22:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('asset_type', models.CharField(blank=True, choices=[('ASSET', 'Asset'), ('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('SYSTEM', 'System'), ('SWITCH', 'Switch'), ('CLUST', 'Clust')], default='', max_length=30)),
                ('vendor', models.CharField(blank=True, default='', max_length=50)),
                ('contract_start', models.DateField(blank=True, default=datetime.date.today)),
                ('contract_end', models.DateField(blank=True, default=datetime.date.today)),
                ('received_date', models.DateField(blank=True, default=datetime.date.today)),
                ('link_to_pdf', models.CharField(blank=True, default='', max_length=2048)),
                ('order_number', models.CharField(blank=True, default='', max_length=30)),
                ('quote', models.CharField(blank=True, default='', max_length=20)),
                ('account', models.CharField(blank=True, default='', max_length=50)),
                ('customer', models.CharField(blank=True, default='', max_length=50)),
                ('customer_PO', models.CharField(blank=True, default='', max_length=20)),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('property_id', models.CharField(blank=True, default='', max_length=30)),
                ('location', models.CharField(default='Genomics 1120A', max_length=30)),
                ('serial_number', models.CharField(blank=True, default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Hardware',
                'verbose_name_plural': 'Hardware',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('vendor_customer_number', models.CharField(blank=True, default='', max_length=30)),
                ('quantity', models.CharField(blank=True, default='', max_length=20)),
                ('part_number', models.CharField(blank=True, default='', max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Software',
                'verbose_name_plural': 'Software',
            },
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Hardware')),
                ('switch_type', models.CharField(choices=[('ETH 1Gb', 'Ethernet 1Gb'), ('ETH 10Gb', 'Ethernet 10Gb'), ('IB', 'Infiniband')], default='', max_length=8)),
            ],
            options={
                'verbose_name': 'Switch',
                'verbose_name_plural': 'Switches',
            },
            bases=('assets.hardware',),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('hardware_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Hardware')),
                ('IP', models.CharField(blank=True, default='', max_length=30, unique=True, validators=[django.core.validators.validate_ipv4_address])),
                ('MAC_address', models.CharField(blank=True, default='', max_length=50, unique=True)),
                ('CPU_cores', models.CharField(blank=True, default='', max_length=5)),
                ('memory_GB', models.CharField(blank=True, default='', max_length=10)),
                ('primary_disk_size_GB', models.CharField(blank=True, default='', max_length=10)),
                ('watts', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'System',
                'verbose_name_plural': 'Systems',
            },
            bases=('assets.hardware',),
        ),
        migrations.CreateModel(
            name='Clust',
            fields=[
                ('system_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.System')),
                ('partition', models.CharField(blank=True, choices=[('HEAD', 'Head'), ('AMD COMPUTE', 'AMD Compute'), ('INTEL COMPUTE', 'Intel Compute'), ('HIGH MEM', 'High Mem'), ('GPU', 'GPU'), ('MISC', 'Misc'), ('HYPERVISOR', 'Hypervisor')], default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Clust',
                'verbose_name_plural': 'Clust',
            },
            bases=('assets.system',),
        ),
    ]
