# Generated by Django 3.0.4 on 2020-03-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20200326_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPUCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(default='gtx 1080', max_length=50)),
            ],
            options={
                'verbose_name': 'GPU Card',
                'verbose_name_plural': 'GPU Cards',
            },
        ),
    ]
