# Generated by Django 3.0.4 on 2020-03-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_gpucard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpucard',
            old_name='card_name',
            new_name='name',
        ),
    ]
