# Generated by Django 3.0.4 on 2020-03-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20200326_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='clust',
            name='GPU_Card',
            field=models.CharField(choices=[('A', 'name'), ('B', 'quantity')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='gpucard',
            name='type',
            field=models.CharField(choices=[('A', 'name'), ('B', 'quantity')], default='', max_length=1),
        ),
    ]
