# Generated by Django 3.0.4 on 2020-03-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20200326_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clust',
            name='GPU_Card',
        ),
        migrations.AlterField(
            model_name='gpucard',
            name='name',
            field=models.CharField(default='GTX 1080', max_length=50),
        ),
        migrations.AlterField(
            model_name='gpucard',
            name='type',
            field=models.CharField(choices=[('A', 'name')], default='', max_length=1),
        ),
    ]
