# Generated by Django 3.0.4 on 2020-03-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20200326_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GPUCard',
        ),
        migrations.AddField(
            model_name='clust',
            name='GPU_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clust',
            name='GPU_quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
