# Generated by Django 3.0.4 on 2020-03-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_auto_20200326_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clust',
            name='GPU_card',
        ),
        migrations.RemoveField(
            model_name='clust',
            name='GPU_quantity',
        ),
        migrations.AddField(
            model_name='system',
            name='GPU_card',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='system',
            name='GPU_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
