# Generated by Django 3.0.4 on 2020-03-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20200326_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='software',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='switch',
            name='switch_type',
            field=models.CharField(blank=True, choices=[('ETH 1Gb', 'Ethernet 1Gb'), ('ETH 10Gb', 'Ethernet 10Gb'), ('IB', 'Infiniband')], default='', max_length=8),
        ),
    ]
